# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'FligthsCodingTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  #use_frameworks!


  # Pods for FligthsCodingTest

    pod 'MagicalRecord', '~> 2.3'
    pod 'AFNetworking', '~> 3.0'
    pod 'MBProgressHUD', '~> 1.0'

  target 'FligthsCodingTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FligthsCodingTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
